### ISSUE TITLE
Radix Theme Provider causes overflow

### ISSUE THREAD

**Issue by bitwhys** [bitwhys/blog#1]
The following bits of code are causing overflow
```css
@supports (min-height: 100dvh) {
  .radix-themes:where([data-is-root-theme="true"]) {
    min-height: 100dvh;
  }
}

themes:where([data-is-root-theme="true"]) {
  position: relative;
  z-index: 0;
  min-height: 100vh;
}
```
